export const OPEN_METAGE_INDEX_DIALOG = 'OPEN_METAGE_INDEX_DIALOG'
export const CLOSE_METAGE_INDEX_DIALOG = 'CLOSE_METAGE_INDEX_DIALOG'
export const OPEN_METAGE_FORM_DIALOG = 'OPEN_METAGE_FORM_DIALOG'
export const CLOSE_METAGE_FORM_DIALOG = 'CLOSE_METAGE_FORM_DIALOG'
